---
title: "Research"
---

### Software Development

* Wrobel, J., Goldsmith, J., **McDonnell, E**. (2020). `registr`: Curve registration for exponential family functional data. R package version 1.0.0. https://cran.r-project.org/web/packages/registr/index.html.

### Publications

* **McDonnell EI**, Zipunnikov V, Schrack JA, Goldsmith J, Wrobel J. Scale-invariant time registration of 24-hour accelerometric rest-activity profiles and its application to human chronotypes. bioRxiv 2020.10.13.337550; doi: https://doi.org/10.1101/2020.10.13.337550.
* Sanders K, Staubitz J, Juárez AP, Marler S, Browning W, **McDonnell E**, et al. Addressing challenging behavior during hospitalizations for children with autism: A pilot applied behavior analysis RCT. Autism Research. 2020; 13(7):1072-1078.  
* McDonald CM, Sajeev G, Yao Z, **McDonnell E**, Elfring G, Souza M, et al. Deflazacort versus prednisone treatment for Duchenne muscular dystrophy: a meta‐analysis of disease progression rates in recent multicenter clinical trials. Muscle & Nerve. 2020; 61(1):26-35.
* Neumeyer AM, Cano Sokoloff N, **McDonnell EI**, Macklin, EA, McDougle CJ, Holmes TM, et al. Nutrition and Bone Density in Boys with Autism Spectrum Disorder. Journal of the Academy of Nutrition and Dietetics. 2018; 118(5):865-877.
* Nicholson K, Murphy A, **McDonnell E**, Shapiro J, Simpson E, Glass J, et al. Improving symptom management for people with amyotrophic lateral sclerosis. Muscle & Nerve. 2018; 57(1):20-24.
* Kuhlthau, KA, **McDonnell E**, Coury DL, Payakachat N, Macklin E. Associations of quality of life with health-related characteristics among children with autism. Autism. 2018; 22(7):804-813.
* Paganoni S, **McDonnell E**, Schoenfeld D, Yu H, Deng J, Atassi H, et al. Functional Decline is Associated with Hopelessness in Amyotrophic Lateral Sclerosis (ALS). Journal of Neurology and Neurophysiology. 2017; 8(2).
* Mruzek DW, McAleavey S, Loring WA, Butter E, Smith T, **McDonnell E**, et al. A pilot investigation of an iOS-based app for toilet training children with autism spectrum disorder. Autism. 2019; 23(2):359–370.
* **McDonnell E**, Schoenfeld D, Paganoni S, Atassi N. Causal inference methods to study gastric tube use in amyotrophic lateral sclerosis. Neurology. 2017; 89(14), 1483-1489.
* Hong TS, Wo JY, Borger DR, Yeap BY, **McDonnell EI**, Willers H, et al. Phase II Study of Proton-Based Stereotactic Body Radiation Therapy for Liver Metastases: Importance of Tumor Genotype. Journal of the National Cancer Institute. 2017; 109(9).
* Marler S, Ferguson, BJ, Lee EB, Peters B, Williams KC, **McDonnell E**, et al. Association of Rigid-Compulsive Behavior with Functional Constipation in Autism Spectrum Disorder. Journal of Autism and Developmental Disorders. 2017; 47(6), 1673-1681.
* Neumeyer AM, Cano Sokoloff N, **McDonnell E**, Macklin EA, McDougle CJ. Bone microarchitecture in adolescent boys with autism spectrum disorder. Bone. 2017; 97:139-146.
* Neumeyer AM, Cano Sokoloff N, **McDonnell EI**, Macklin EA, McDougle CJ, Misra M. Bone accrual of males with autism spectrum disorder. Journal of Pediatrics. 2017; 181:195-201. 
* Ferguson BJ, Marler S, Altstein LL, Lee EB, Akers J, Sohl K, McLaughlin A, Hartnett K, Kille B, Mazurek M, Macklin EA, **McDonnell E**, et al. Psychophysiological associations with gastrointestinal symptomatology in autism spectrum disorder. Autism Research. 2017; 10(2):276-288.
* Ferguson BJ, Marler S, Altstein LL, Lee EB, Mazurek MO, McLaughlin A, Macklin EA, **McDonnell E**, et al. Associations between cytokines, endocrine stress response, and gastrointestinal symptoms in autism spectrum disorder. Brain, Behavior and Immunity. 2016; 58:57-62.
* Redjal N, Reinshagen C, Le A, Walcott BP, **McDonnell E**, Dietrich J, et al. Valproic acid, compared to other antiepileptic drugs, is associated with improved overall and progression-free survival in glioblastoma but worse outcome in grade II/III gliomas treated with temozolomide. Journal of Neuro-Oncology. 2016; 127(3):505-14.
* Hong TS, Wo JY, Yeap BY, Ben-Josef E, **McDonnell EI**, Blaszkowsky LS, et al. Multi-institutional phase II study of high-dose hypofractionated proton beam therapy in patients with localized, unresectable hepatocellular carcinoma and intrahepatic cholangiocarcinoma. Journal of Clinical Oncology. 2016; 34(5):460-8.
* Marler S, Ferguson BJ, Lee EB, Peters B, Williams KC, **McDonnell E**, et al. Brief report: Whole blood serotonin levels and gastrointestinal symptoms in autism spectrum disorder. Journal of Autism and Developmental Disorders. 2016; 46(3):1124-30.
* Fournier CN, Murphy A, Loci L, Mitsumoto H, Lomen-Hoerth C, Kisanuki Y, Simmons Z, Margakis NA, McVey AL, Al-Lahham T, Heiman-Patterson TD, Andrews J, **McDonnell E**, et al. Primary lateral sclerosis and
early upper motor neuron disease: Characteristics of a cross-sectional population. Journal of Clinical Neuromuscular Disease. 2016; 17(3):99-105.
* Ferrone CR, Marchegiani G, Hong TS, Ryan DP, Deshpande V, **McDonnell EI**, et al. Radiological and surgical implications of neoadjuvant treatment with FOLFIRINOX for locally advanced and borderline resectable pancreatic cancer. Annals of Surgery. 2015; 261(1):12-7.

### Conference Posters and Presentations

* **McDonnell E**, Xie S, Marder K, Wang Y. Smooth time-varying Gaussian graphical models to study disease progression [Abstract]. To be presented at the Joint Statistical Meetings, Virtual, 2020.
* **McDonnell E**, Wrobel J, Goldsmith J, Zipunnikov V. Curve registration to identify circadian rhythm chronotypes in accelerometer data [Abstract]. Presented at the Joint Statistical Meetings, Denver, CO, 2019.
* Signorovitch J, Schilling T, Sajeev G, Yao Z, **McDonnell E**, Elfring G, et al. Deflazacort or Prednisone treatment for Duchenne muscular dystrophy: A meta-analysis of disease progression rates in recent multicenter clinical trials [Abstract]. Presented at the American Academy of Neurology 71st Annual Meeting, Philadelphia, PA 2019.
* Dyer MA, **McDonnell EI**, Yeap BY, Depauw N, Wolfgang JA, Wo JY, et al. Change in platelet count and normal liver dosimetry in patients receiving proton radiation therapy for unresectable hepatocellular carcinoma or intrahepatic cholangiocarcinoma [Abstract]. Presented at the American Society for Radiation Oncology (ASTRO) Annual Meeting, Boston, MA, 2016.
* Hong T, Wo J, **McDonnell E**, Yeap B, Drapek L, Wolfgang J, et al. A single arm phase 2 study of individualized proton-based stereotactic body radiation therapy (P-SBRT) of liver metastases [Abstract]. Presented at the American Society for Radiation Oncology (ASTRO) Annual Meeting; San Antonio, TX 2015.
* Wo J, Zhu A, **McDonnell E**, Yeap B, Borger D, Iafrate A, et al. Clinical and molecular predictors of local failure after SBRT for liver metastases: A secondary analysis of a prospective phase II trial [Abstract]. Presented at the American Society for Radiation Oncology (ASTRO) Annual Meeting; San Antonio, TX 2015.
* Hong T, Wo J, Yeap B, Ben-Josef E, **McDonnell E**, Drapek L, et al. Multi-institutional phase II study of high dose, hypofractionated proton beam therapy (HF-PBT) for unresectable primary liver cancers: Long term outcomes in patients (pts) with intrahepatic cholangiocarcinoma (ICC) [Abstract]. Presented at the American Society of Clinical Oncology (ASCO) Annual Meeting; Chicago, IL 2015.
* Kuhlthau K, **McDonnell E**, Payakachat N, Coury D, Delahaye J, Macklin E, editors. Correlates of cross-sectional and longitudinal health-related quality of life among children with autism spectrum disorders [Abstract]. Presented at the International Meeting for Autism Research (IMFAR); 2015; Salt Lake City, UT.
* Marler S, Lee E, Anderson G, Ferguson B, **McDonnell E**, Beversdorf D, et al. Gastrointestinal symptoms, whole blood serotonin levels, and behavioral symptoms in children and adolescents with autism spectrum disorder [Abstract]. Presented at the International Meeting for Autism Research (IMFAR); Salt Lake City, UT 2015.
* Ferguson B, Marler S, Lee E, Akers J, Mazurek M, Sohl K, Hartnett K, Macklin EA, **McDonnell E**, et al. Psychophysiological predictors of gastrointestinal symptomatology in autism spectrum disorder [Abstract]. Presented at the International Meeting for Autism Research (IMFAR); Salt Lake City, UT 2015.
* **McDonnell E**. Analyzing supportive care in ALS [Oral presentation]. Presented at Statistical Issues in the Analysis of Neurological Studies: A Harvard Catalyst Biostatistics Symposium; Boston, MA 2014.
* Murphy A, **McDonnell E**, Wolff J, Shapiro J, Simpson E, Glass J, et al. Improving symptom management for people with amyotrophic lateral sclerosis (ALS) [Abstract]. Presented at the Northeast Amyotrophic Lateral Sclerosis Consortium (NEALS) Annual Meeting; Clearwater Beach, FL 2013.
* Paganoni S, **McDonnell E**, Schoenfeld D, Yu H, Deng J, Atassi H, et al. Longitudinal study of mood in ALS [Abstract]. Presented at the Northeast Amyotrophic Lateral Sclerosis Consortium Annual Meeting; Clearwater Beach, FL 2013.